systemsim_bd: update afer immutable biovecs changes
Kernel 3.14 made biovecs immutable. Update bogus disk accordingly. In-kernel
drivers were updated in commit 7988613b0e5b2638caf6cd493cc78e9595eba19c
(block: Convert bio_for_each_segment() to bvec_iter).

This fixes the following build error:
drivers/block/systemsim_bd.c: In function ‘do_systemsim_bd_request’:
drivers/block/systemsim_bd.c:161: error: incompatible types when assigning to type ‘struct bio_vec *’ from type ‘struct bio_vec’
drivers/block/systemsim_bd.c:161: warning: left-hand operand of comma expression has no effect
drivers/block/systemsim_bd.c:161: error: request for member ‘bv_len’ in something not a structure or union
drivers/block/systemsim_bd.c:175: error: incompatible types when assigning to type ‘struct bio_vec *’ from type ‘struct bio_vec’
drivers/block/systemsim_bd.c:175: warning: left-hand operand of comma expression has no effect
drivers/block/systemsim_bd.c:175: error: request for member ‘bv_len’ in something not a structure or union
make[2]: *** [drivers/block/systemsim_bd.o] Error 1
make[1]: *** [drivers/block] Error 2
make: *** [drivers] Error 2

Signed-off-by: Mark Nelson <mdnelson8@gmail.com>