systemsim_net: include module.h header file
To fix this compile error:
  CC      drivers/net/ethernet/ibm/systemsim_net.o
drivers/net/ethernet/ibm/systemsim_net.c:395: error: expected declaration specifiers or ‘...’ before string constant
drivers/net/ethernet/ibm/systemsim_net.c:395: warning: data definition has no type or storage class
drivers/net/ethernet/ibm/systemsim_net.c:395: warning: type defaults to ‘int’ in declaration of ‘MODULE_DESCRIPTION’
drivers/net/ethernet/ibm/systemsim_net.c:395: warning: function declaration isn’t a prototype
drivers/net/ethernet/ibm/systemsim_net.c:396: error: expected declaration specifiers or ‘...’ before string constant
drivers/net/ethernet/ibm/systemsim_net.c:396: warning: data definition has no type or storage class
drivers/net/ethernet/ibm/systemsim_net.c:396: warning: type defaults to ‘int’ in declaration of ‘MODULE_LICENSE’
drivers/net/ethernet/ibm/systemsim_net.c:396: warning: function declaration isn’t a prototype
make[4]: *** [drivers/net/ethernet/ibm/systemsim_net.o] Error 1
make[3]: *** [drivers/net/ethernet/ibm] Error 2
make[2]: *** [drivers/net/ethernet] Error 2
make[1]: *** [drivers/net] Error 2
make: *** [drivers] Error 2

we need to add the #include for linux/module.h

Signed-off-by: Mark Nelson <mdnelson8@gmail.com>