systemsim_net: remove asm/system.h
Kernel 3.4 removed the asm/system.h header files from every architecture
including powerpc, so remove it from systemsim_net as well.

This fixes the following build failure:
drivers/net/ethernet/ibm/systemsim_net.c:55:24: error: asm/system.h: No such file or directory

See commit ae3a197e3d0bfe3f4bf1693723e82dc018c096f3 (Disintegrate asm/system.h
for PowerPC) for where the header file was removed.

Signed-off-by: Mark Nelson <mdnelson8@gmail.com>